Development/recipes-project-2.0/config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  
  devise_for :users
  post '/rate' => 'rater#create', :as => 'rate'
  resources :recipes do
    resources :ingredients
  end

end

Development/recipes-project-2.0/app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

Development/recipes-project-2.0/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
  validates :name, :presence => true
end

Development/recipes-project-2.0/app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

Development/recipes-project-2.0/app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

end

Development/recipes-project-2.0/app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

Development/recipes-project-2.0/app/models/recipe.rb
class Recipe < ActiveRecord::Base
  ratyrate_rateable "recipe_ratings"
  
  belongs_to :user
  has_many :ingredients
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  validates :name, :presence => true
  #accepts_nested_attributes_for :ingredients_attributes
  #def ingredients_attributes=(ingredients_attributes)
  #  ingredients_attributes.values.each do |ingredients|
  #    ingredient = Ingredient.find_or_create_by(name: ingredient)
  #    self.recipe_ingredients.build(:ingredient => ingredient)
  #    end
  #  end
  #end
  def ingredients_attributes=(ingredients_attributes)
    ingredients_attributes.values.each do |ingredient|

      if !(ingredient["name"] == "")
        ingredient = Ingredient.find_or_create_by(name: ingredient)
        self.recipe_ingredients.build(:ingredient => ingredient)
      end
    end
  end
end

Development/recipes-project-2.0/app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  belongs_to :recipe 
  belongs_to :ingredient
end

Development/recipes-project-2.0/app/models/user.rb
class User < ActiveRecord::Base
  ratyrate_rater

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Development/recipes-project-2.0/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #helper_method :current_user

  #def current_user
  #  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  #end

  #def require_user
  #  redirect_to '/login' unless current_user
  #end

end

Development/recipes-project-2.0/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

Development/recipes-project-2.0/app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

Development/recipes-project-2.0/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
end

Development/recipes-project-2.0/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  #before_action :require_user, only: [:create, :show, :edit, :update, :destroy]
  before_action :find_recipes, only: [:index]
  
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      
      redirect_to recipes_path(@recipe)
    else
      render 'new'
    end
  end

  def show
    find_recipe
  end

  def edit
    find_recipe
  end

  def update
    find_recipe
    if @recipe.update(recipe_params)

      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    find_recipe
    @recipe.destroy

    redirect_to root_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, ingredients_attributes: :name)
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def find_recipes
    @recipe = Recipe.find_by(params[:id])
  end

end

Development/recipes-project-2.0/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_url 
    else
      redirect_to login_url
    end
  end

  def destroy
    session.destroy
    redirect_to root_url
  end

end

Development/recipes-project-2.0/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id 
      redirect_to root_path
    else
      redirect_to signup_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
  
end

Development/recipes-project-2.0/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @recipes = Recipe.all
    @user = current_user 
  end
  
end

Development/recipes-project-2.0/app/helpers/comments_helper.rb
module CommentsHelper
end

Development/recipes-project-2.0/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

Development/recipes-project-2.0/app/helpers/ratings_helper.rb
module RatingsHelper
end

Development/recipes-project-2.0/app/helpers/recipes_helper.rb
module RecipesHelper
end

Development/recipes-project-2.0/app/helpers/sessions_helper.rb
module SessionsHelper
end

Development/recipes-project-2.0/app/helpers/users_helper.rb
module UsersHelper
end

Development/recipes-project-2.0/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Development/recipes-project-2.0/app/views/recipes/edit.html.erb
<%= form_for(@recipe) do |r| %>
  <%= r.label :name %>
  <%= r.text_field :name %><br>

  <% @recipe.ingredients.each do |ingredient| %>
    <li><%= ingredient.name %></li>
  <% end %>
  <%= r.submit %>
<% end %>

Development/recipes-project-2.0/app/views/recipes/index.html.erb
<div class="container">
  <div class="jumbotron">
      <h5>Welcome, </h5>
      <h2>Recipe Site</h2>

      <p>This rails app allows you to create your recipe along with its ingredients. Have fun creating great foods to eat.</p>

      <h3>All Recipes:</h3>
      <% @recipes.each do |recipe| %>
        <li><%= link_to recipe.name, recipe_path(recipe) %></li>
      <% end %>
      <div class="small-2 large-4 columns">
        <% if @recipes.any? %>
         Recipe ratings: <%= rating_for @recipe, "recipe_ratings" %>
          <br>
        <% end %>
      </div>
      <%= button_to 'Create New Recipe', new_recipe_path, method: 'get' %>
  </div>
</div>

Development/recipes-project-2.0/app/views/recipes/new.html.erb
<%= form_for(@recipe) do |r| %>
  <%= r.label :name %>
  <%= r.text_field :name %><br><br>

  <%= r.fields_for :ingredients_attributes do |ingredient| %>
    <%= ingredient.label 'Ingredients:' %>
    <%= ingredient.text_field :name %>
  <% end %>

  <%= r.submit %>
<% end %>

Development/recipes-project-2.0/app/views/recipes/show.html.erb
<h1><%= @recipe.name.capitalize %></h1>

<h3>Ingredients:</h3>

<ol>
  <% @recipe.ingredients.each do |ingredient| %>
   <li><%= ingredient.name %></li><br>
  <% end %>
</ol>

<%= button_to "Add Ingredients", new_recipe_ingredient_path(@recipe), method: 'get' %>
<!--%= button_to "Edit Ingredients", routes not working!!!    edit_recipe_ingredient_path(@ingredient), method: 'get' %-->  
<%= button_to "Edit Recipe", edit_recipe_path(@recipe), method: 'get' %>  
<%= button_to "Delete Recipe", "/recipes/{@recipe.id}", method: 'delete' %>